### ISSUE TITLE
Use CSS class-prefixes in order to avoide conflicts with extensions and pages that use bootstrap as well

### ISSUE THREAD

**Issue by DavidSporer** [mittwald/typo3-forum#106]
typo3_forum uses bootstrap and seems to have some custom classes.
This causes problems when the page where it's included also depends on bootstrap.
Please use prefixes for the custom css-classes and don't modify the standard bootstrap classes in order to avoid that.

**Comment by kpurrmann** [comment]
Split up bootstrap template in version 1.0.1
