### ISSUE TITLE
Missing Tables

### ISSUE THREAD

**Issue by NyroTheCat** [mittwald/typo3-forum#111]
Hi,
i want to evaluate this plugin. i made a fresh and clean typo3 installation and added this plugin. i followed the setup instructions. as soon as i create an acl the site stops working and gives me an error code.
i turned on the debug wich noticed me about missing tables. eg:
`'db.tx_typo3forum_domain_model_user_frontendusergroup' doesn't exist`

Typo3 7.6.3
typo3_forum 1.0.0

**Comment by velletti** [comment]
This looks like missing TYPO Script settings: Please add typo3Forums static Template settings to Your template. After that clear Cache and the message about missing mapping from domain Modell to exisitng fe user Table should go away .. 

if so, please close this issue ...

**Comment by NyroTheCat** [comment]
Thanks 4 your reply. The Error Output has gone. But the forum is still not rendered. As long the ACL is active it gives me an ErrorCode like `Oops, an error occurred! Code: 201602261449345a08b65e`.

**Comment by velletti** [comment]
Have a look into TYPO3 backends Sys Log, there should be a detailed error PHP error info about this timestamp 201602261449345a08b65e code .. 
I think the FE user Object is not correct.
