### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by alat54** [mittwald/typo3-forum#113]
When i check the database, the helper of typo3 said me :
`Database analyzer
Change fields

    select/deselect all
    ALTER TABLE tx_typo3forum_domain_model_format_textparser CHANGE type type varchar(64) NOT NULL default '\Mittwald\Typo3Forum\Domain\Model\Format\BBCode';
    Current value: varchar(64) NOT NULL default 'MittwaldTypo3ForumDomainModelFormatBBCode'
    ALTER TABLE tx_typo3forum_domain_model_moderation_report CHANGE type type varchar(64) NOT NULL default '\Mittwald\Typo3Forum\Domain\Model\Moderation\UserReport';
    Current value: varchar(64) NOT NULL default 'MittwaldTypo3ForumDomainModelModerationUserReport'
    ALTER TABLE tx_typo3forum_domain_model_user_notification CHANGE type type varchar(64) NOT NULL default '\Mittwald\Typo3Forum\Domain\Model\Forum\Post';
    Current value: varchar(64) NOT NULL default 'MittwaldTypo3ForumDomainModelForumPost'
`

I tried several methods to insert data directly in base... with \\, \\\\ but even if insert is good and data is inserted correctly (with the good caracter conversion', the backoffice said me something was wrong...

Can you help me please?

**Comment by alat54** [comment]
Hi, 

With the master i have new error (last is already here)

`array(4 items)
   caller => "TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery" (60 chars)
   ERROR => "Table 't3_minisites.tx_typo3forum_domain_model_user_frontenduser' doesn't ex
      ist" (79 chars)
   lastBuiltQuery => "SELECT  tx_typo3forum_domain_model_user_frontenduser.* FROM tx_typo3forum_do
      main_model_user_frontenduser  WHERE tx_typo3forum_domain_model_user_frontend
      user.uid = '1' LIMIT 1" (174 chars)
   debug_backtrace => "call_user_func#34 // {closure}# // TYPO3\CMS\Frontend\Http\Application->run#
      33 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#78 // TYPO3\CMS\Frontend\
      Http\RequestHandler->handleRequest#302 // TYPO3\CMS\Frontend\Controller\Typo
      ScriptFrontendController->INTincScript#232 // TYPO3\CMS\Frontend\Controller\
      TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent#347
      7 // TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScrip
      t_process#3511 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cO
      bjGetSingle#3566 // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->
      render#859 // TYPO3\CMS\Frontend\ContentObject\UserContentObject->render#943
       // TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction
      #40 // call_user_func_array#7315 // TYPO3\CMS\Extbase\Core\Bootstrap->run# /
      / TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest#193 // TYPO3\CMS\Extbase\M
      vc\Web\FrontendRequestHandler->handleRequest#206 // TYPO3\CMS\Extbase\Mvc\Di
      spatcher->dispatch#69 // TYPO3\CMS\Extbase\Mvc\Controller\ActionController->
      processRequest#86 // Mittwald\Typo3Forum\Controller\AbstractController->call
      ActionMethod#176 // TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callA
      ctionMethod#123 // call_user_func_array#283 // Mittwald\Typo3Forum\Controlle
      r\ForumController->indexAction# // Mittwald\Typo3Forum\Service\Authenticatio
      n\AuthenticationService->assertReadAuthorization#76 // Mittwald\Typo3Forum\S
      ervice\Authentication\AuthenticationService->assertAuthorization#79 // Mittw
      ald\Typo3Forum\Service\Authentication\AuthenticationService->checkAuthorizat
      ion#148 // Mittwald\Typo3Forum\Service\Authentication\AuthenticationService-
      >getCacheIdentifier#168 // Mittwald\Typo3Forum\Service\Authentication\Authen
      ticationService->getUserGroupIdentifier#191 // Mittwald\Typo3Forum\Service\A
      uthentication\AuthenticationService->getUser#203 // Mittwald\Typo3Forum\Doma
      in\Repository\User\FrontendUserRepository->findCurrent#220 // TYPO3\CMS\Extb
      ase\Persistence\Reposito..." (2940 chars)`

**Comment by alat54** [comment]
I have delete all files, empty database before install the master...

**Comment by velletti** [comment]
Looks as if the Typo3Forum Template setup.txt ist not loaded to your SITE Template 

so no TYPO Script settings can do the mapping from TYPO3 fe user model to Typo3 fe_user Database .. 
just include the typo3Forum Script should help in this case

**Comment by velletti** [comment]
double to :
https://github.com/mittwald/typo3-forum/issues/102

**Comment by alat54** [comment]
All extension TS are included in my template.

Thanks
