### ISSUE TITLE
No buttons for creating topic. multi language site bug with creation of forums.

### ISSUE THREAD

**Issue by Naberd** [mittwald/typo3-forum#116]
We have multiple languages on our site. Installed forum extension with bootstrap template included ( had to comment old bootstrap and jquery plugins ) otherwise our plugin which uses newer ones will not work anymore.
Set in template config storagePid and pids for forum.
Created in backend forum with child.
at frontend we have nothing displayed.
after debug found out that it executes query to select root forum where sys_language_uid = x, in database that forum has sys_language_uid = 0, meaning it will never be displayed.

adjusted the value in database to match up forum query, i see main forum but no sub forum and have no option to create new  topics/ posts.

**Comment by hogiro** [comment]
I dont see any create new topics / posts buttons either.

**Comment by kpurrmann** [comment]
@Naberd Will check that language issue. 

"Create topic/post" - button should be available if an ACL is provided. If there is no ACL, buttons will never been shown.

**Comment by hogiro** [comment]
even after creating and using ACL's I cannot see any buttons.

**Comment by kpurrmann** [comment]
Did you configured the constants? 
You have to define where forum data has to be stored and on which page current forum plugin is inserted. 

If you have, could you please give some information on your TYPO3 version and installed extensions like realurl? May this issue is related to an javascript issue on fixed #119.

**Comment by Naberd** [comment]
From what i see in javascript error is following error Failed to load resource: the server responded with a status of 404 (Not Found) http://www.simco-ion.nl/index.php?id=458&eID=typo3_forum&language=de&tx_typo3forum_ajax[controller]=Ajax&tx_typo3forum_ajax[action]=main&tx_typo3forum_ajax[format]=json

458 is id of storage folder where all data for forum is located,  language=de that's really strange because language at this moment is 1 which stands for nl, opened that url in new window with language=nl,  still get 404 back.  changed id to the id of the page 675 it gives empty array back.

So it seem that it can't acces folders  from frontend.

typo3 version is 7.6.5 site was migrated last year from version 4.x to version 6.2.3 and this year from 6.2.3 to 7.6.5

**Comment by kpurrmann** [comment]
Problem seems that the ajax call is made on page id 458. It should be the current page where your forum plugin is located. It can be changed by 
`plugin.tx_typo3forum.settings.pids.Forum = {your page uid of forum plugin}`

**Comment by Naberd** [comment]
That is what i have in my typoscript for forum:
`plugin.tx_typo3forum {
  persistence {
    storagePid = 458
  }
  settings {
    pids {
      Forum = 675
    }
  }
}`

**Comment by kpurrmann** [comment]
Ok found the problem:
Look at: `http://www.simco-ion.de/typo3conf/ext/typo3_forum/Resources/Public/Javascript/forum.js` First 3 lines. 

```
if (typeof currentPageUid === 'undefined' || currentPageUid === null) {
var currentPageUid = 458;
}
```


Someone edited the default forum.js.

**Comment by Naberd** [comment]
removed the confusing page id from forum.js: var currentPageUid;
on forum page it's defined so it gives always 675 back  log from console:
currentPageUid
"675"
