### ISSUE TITLE
Forum.js javascript bugs

### ISSUE THREAD

**Issue by Naberd** [mittwald/typo3-forum#118]
First of all to make it better compatible with other extensions which use other javascript libraries.
to replace
`$(document).ready(function () {`
with:
`jQuery(document).ready(function ($) {`

another issue it seem if you have loaded template of forum on root level, forum.js is loaded on every page which causes javascript errors: currentPageUid is not defined. to solve it we need to add the following code:
```
if (typeof currentPageUid === 'undefined') {
var currentPageUid;
}
```

**Comment by Samuel-Weiss** [comment]
I have the same problem with the inline JS in the File: `typo3_forum/Classes/ViewHelpers/Form/BbCodeEditorViewHelper.php`
Additionally its cause a problem if I load jquery in the Footer

**Comment by pstranghoener** [comment]
Could please add that to your TS:

page.includeJSFooterlibs {
    typo3forum_jquery >
    typo3forum_bootstrap >
}

We will add that to the Documentation

**Comment by Samuel-Weiss** [comment]
I still get the `Uncaught ReferenceError: $ is not defined` error.
changing in File `typo3_forum/Classes/ViewHelpers/Form/BbCodeEditorViewHelper.php` 107
`' . 'var bbcodeSettings = ' . json_encode($this->getPanelSettings()) . ';' . 'window.onload = function() {' . '$(\'#' . $this->arguments['id'] . '\').markItUp(bbcodeSettings);' . '}; </script>';`
would solve my problem
