### ISSUE TITLE
forum.js without BaseURL

### ISSUE THREAD

**Issue by Samuel-Weiss** [mittwald/typo3-forum#119]
Hy
I have a Problem with the Ajax Loading if i disable the Base-URL.
adding a / to the Ajax URL solved it for me
`url: "/index.php?id="+currentPag...`

'version' => '1.0.1'

**Comment by kpurrmann** [comment]
Could not not reproduce error.
Need more information on this. 

TYPO3 version? RealUrl?

Why u should disable the baseUrl? Or just use `config.absRefPrefix` as recommended.

**Comment by Samuel-Weiss** [comment]
I Use Typo 6.2 with Real URL.
The `config.absRefPrefix = /` is configured. We haven't a <base> Tag in the header

**Comment by kpurrmann** [comment]
+1 Fixed, will be updated in next release
