### ISSUE TITLE
Fatal error: Cannot access protected property 

### ISSUE THREAD

**Issue by osnevi** [mittwald/typo3-forum#125]
I get the following Error after entering a Forum in the deepest level.
Example Link: http://www.explortal-logistics.net/explortal-logistics/ask-answer/forum-test.html?cHash=cb6d21b8a67e56e6e4c1b242882b27ae&tx_typo3forum_pi1[forum]=17&tx_typo3forum_pi1[action]=show&tx_typo3forum_pi1[controller]=Forum

This is the error message:
Fatal error: Cannot access protected property Mittwald\Typo3Forum\Domain\Model\Forum\Forum::$criteria in /html/typo3/typo3_src-6.2.19/typo3/sysext/extbase/Classes/Persistence/Generic/LazyLoadingProxy.php on line 105

Would be great to get a reason/solution for this error.

**Comment by kpurrmann** [comment]
Fixed in next release.
