### ISSUE TITLE
SQL Error ext_tables_static+adt.sql

### ISSUE THREAD

**Issue by Samuel-Weiss** [mittwald/typo3-forum#126]
I wasn't `able to import the ext_tables_static+adt.sql` File

SQL query:
```
INSERT INTO tx_typo3forum_domain_model_format_textparser VALUES ('1', '0', '\Mittwald\Typo3Forum\Domain\Model\Format\BBCode', 'Bold', 'tx-typo3forum-miu-bold', '[b]|[/b]', '/\\[b\\](.*)\\[\\/b\\]/i', '<b>\\1</b>', NULL, NULL, '1288879482', '1284727514', '0', '0', '0', '0', '0', '', '0', '0', '0', '0', '0', '0', '0', 'a:5:{s:4:"type";N;s:4:"name";N;s:4:"icon";N;s:18:"regular_expression";N;s:30:"regular_expression_replacement";N;}');
MySQL said: Documentation

#1136 - Column count doesn't match value count at row 1 
```

Also there is an inconsistency between` '\Mittwald\Typo3Forum\Domain\Model\Format\BBCode'` and 
` Mittwald\Typo3Forum\Domain\Model\Format\AbstractTextParserElement.subclasses .Mittwald\Typo3Forum\Domain\Model\Format\BBCode = Mittwald\Typo3Forum\Domain\Model\Format\BBCode`

**Comment by abeutel** [comment]
Also, the type field entries must not start with a backslash, the logged query was
```SELECT tx_typo3forum_domain_model_format_textparser.* FROM tx_typo3forum_domain_model_format_textparser  WHERE 1=1 AND (tx_typo3forum_domain_model_format_textparser.type='Mittwald\\Typo3Forum\\Domain\\Model\\Format\\BBCode' OR tx_typo3forum_domain_model_format_textparser.type='Mittwald\\Typo3Forum\\Domain\\Model\\Format\\QuoteBBCode' OR tx_typo3forum_domain_model_format_textparser.type='Mittwald\\Typo3Forum\\Domain\\Model\\Format\\ListBBCode') AND (tx_typo3forum_domain_model_format_textparser.sys_language_uid IN (0,-1)) AND tx_typo3forum_domain_model_format_textparser.pid IN (0) AND tx_typo3forum_domain_model_format_textparser.deleted=0 AND tx_typo3forum_domain_model_format_textparser.t3ver_state<=0 AND tx_typo3forum_domain_model_format_textparser.pid<>-1 AND tx_typo3forum_domain_model_format_textparser.hidden=0 ORDER BY tx_typo3forum_domain_model_format_textparser.uid ASC```

**Comment by abeutel** [comment]
Provided an updated file (that worked for me) in #128

**Comment by Samuel-Weiss** [comment]
Thanks
I Think `typo3_forum/Configuration/TCA/tx_typo3forum_domain_model_format_textparser.php` Line 34-38, 92-96 should beginn without a \ in `\Mittwald\Typo3Forum\`
