### ISSUE TITLE
MySQL-Table max 64 characters 

### ISSUE THREAD

**Issue by Samuel-Weiss** [mittwald/typo3-forum#127]
I can't create the 'tx_typo3forum_domain_model_moderation_reportworkflowstatus_followup' Table
`#1103 - Incorrect table name 'tx_typo3forum_domain_model_moderation_reportworkflowstatus_followup' `
According to http://dev.mysql.com/doc/refman/5.0/en/identifiers.html the table name ist to long (max. 64 characters)

**Comment by abeutel** [comment]
@Samuel-Weiss And obviously a known issue https://github.com/mittwald/typo3-forum/blob/master/Classes/Scheduler/DatabaseMigrator.php#L125 :-(

**Comment by kpurrmann** [comment]
With #128 and #129 should be fixed because table will not be used anymore.
