### ISSUE TITLE
AJAX Dispatcher - initializeTsfe()

### ISSUE THREAD

**Issue by wr-lang** [mittwald/typo3-forum#138]
`$GLOBALS['TSFE'] = GeneralUtility::makeInstance('tslib_fe', $GLOBALS['TYPO3_CONF_VARS'], GeneralUtility::_GP('id'), GeneralUtility::_GP('type'), true);`

should be

`$GLOBALS['TSFE'] = GeneralUtility::makeInstance('TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController', $GLOBALS['TYPO3_CONF_VARS'], GeneralUtility::_GP('id'), GeneralUtility::_GP('type'), true);`

otherwise an error will be thrown (at least in TYPO3 v7):

> Fatal error:  Class 'tslib_fe' not found in ...\typo3\sysext\core\Classes\Utility\GeneralUtility.php on line 4545

**Comment by macjohnny** [comment]
this has been fixed and could be closed

**Comment by macjohnny** [comment]
@martin-helmich can you close this?
