### ISSUE TITLE
Problem with own template / TS

### ISSUE THREAD

**Issue by billbo85** [mittwald/typo3-forum#148]
Hi all

I'm sorry for my newbi post, but I have no idea how I can fix my issue. 

With bootstrap_package as template I have no problem. I see topic / posts and their create button. But if I include my own extension (template) I also see my created topic / posts, but I don't see the create button. So I think anything is wrong in my template or TS, which prevent "mmf:authentication.ifAccess" command or so, but I have no idea what or where. Do you have inputs which could help me to solve the issue?

**Comment by pstranghoener** [comment]
Hey,

may be you have another bootstrap version in you own template? 

Best Regards Philipp

**Comment by billbo85** [comment]
Hey,
I have tried several bootstrap versions in my own template. e.g. 3.3.5 or 3.3.7.  
There I've included bootstrap.min.css / bootstrap.min.js in template. Maybe there is something missing? But I have no idea what..

Regards
Billy

**Comment by billbo85** [comment]
Bug fixed.

I included Bootstrap.min.js version 3.3.7 and jquery.min.js version 2.2.1 on the bottom of template (under the footer). Problem was the jquery version which was missing and was not loaded.
