### ISSUE TITLE
No "create new topic" Button in clean typo3 installation

### ISSUE THREAD

**Issue by sxbxstxxn** [mittwald/typo3-forum#149]
I installed a clean Typo3 7.6.9 and typo3_forum with this installation guide:
http://typo3-forum.readthedocs.io/en/master/Configuration/Installation/Index.html
I can see all the forums, but there is no "Create new topic" Button. I set the ACLs to "Everyone" but now have no idea what is the problem... I can create new topics in Backend and they were shown.

**Comment by mavoIn** [comment]
hi, do your frontend user have the additional extbase groups?

**Comment by velletti** [comment]
That are all possible Reasons i know:

-> Frontend User is not extbase Type "Typo3forum FE user" : See TYPOScript of typo3forum the expected extbaseType 

-> No Frontend user logged in
-> Backend User is also logged in in SAME Brower session and so Frontgroup Access is calculated wrong
-> TYPO3 Cache -> clear Cache in Installtool and maybe also delete the sub folders in typo3temp
-> Forumsection Access Rights not set for that users Usergroups : He need rights Createand Edit
-> TYPOSCRIPT for TYPO3 Forum not included -> include it and clear the typo3 cache 
-> PageID for Forum or FrontendUser is not set correctly to your Installation (see TypoScript) -> correct id and clear the typo3 cache 
-> EDIT Button is loaded via AJAX: so maybe also a javaScript error can break frontendOutput: -> Use FireBug, Crome Developer Console or something else to see if there are any Error messages. Maybe Old Bootstrap javascript or old jQuerey Version get in conflict.  

Some More hints
-> Multilingual Setup and your syslanguage setup is not setup correctly
-> RealUrl Issue -> disable RealUrl if this helpes .. 
-> does it work with the default templates?
-> check the included javascript if this is working for your Propose
-> maybe it is better to disable the TYPO3FORUM settings in Typoscript for jQuery and bootstrap and use your own settings.

**Comment by sxbxstxxn** [comment]
I think the problem was a multiple load of jquery and bootstrap. After removing that, there is the button. So propably the javascript error was the problem... Thx for help !
