### ISSUE TITLE
No "upload attachment"-Button in frontend

### ISSUE THREAD

**Issue by brainfuck666** [mittwald/typo3-forum#150]
Hey there,
first of all, thanks for the proper typo3 forum! 

Is there a way to upload attachments in the frontend? I'm missing a button or something like this. Or is there simply no way to upload attachments when editing or creating posts?

**Comment by magu81** [comment]
This will be a great feature -  so it make sense !

**Comment by velletti** [comment]
if you have included the typoscript of typo3forum and use the default templates, there are the possability to upload files. 

see source Code of used form Template 

EDIT/ Create
https://github.com/mittwald/typo3-forum/blob/develop/Resources/Private/Partials/Bootstrap/Post/Form.html

or Show Post
https://github.com/mittwald/typo3-forum/blob/develop/Resources/Private/Partials/Bootstrap/Post/Single.html

and search for attachment ... 
PS: This is not a bug or wish (only i need help to configure my Forum) and should be closed

**Comment by brainfuck666** [comment]
Thanks for your response!

I set up the forum according to the tutorial. Hence, the typoscript is included as well as the default templates. Everthing works fine, I am able to create posts, comments, do moderation stuff etc. Except that there's simply no button or upload dialog where it should be according to the templates.

So, do you have any clue where my problem might be? Or any idea how to find it out by my self? 

Best regards

**Comment by magu81** [comment]
The same concerning me also - i`m unable to see some upload / attachement button or some other textediting Icons !

**Comment by magu81** [comment]
can you give an example please - how to do  !

**Comment by magu81** [comment]
remember that nobody was born as an typo3 expert, but everybody can be one !

**Comment by brainfuck666** [comment]
I can see those textediting icons above the textbox...

@magu81  have you included the typo3_forum bootstrap template in your "include static template" options?

**Comment by magu81** [comment]
@brainfuck666 
i did all descripted above -  included the TS in the PAGE which contains the Forum Plugin - i included the TSetup and the Constants also.
The bootstrap is also as Template included --- but it seems not working properly.  I only can send post / replys with no text-Formatting and / or upload some images !

**Comment by magu81** [comment]
have i do some modifications in the Classes via php ?    is the sentence i TS-Setup on the ForumsPage correct with 

mod.web_list {
	deniedNewTables := addToList(tx_typo3forum_domain_model_forum_access,tx_typo3forum_domain_model_forum_attachment,tx_typo3forum_domain_model_moderation_reportcomment,tx_typo3forum_domain_model_user_privatemessage_text)
}

it concernes the ,,deniedNewTables"    .. i also tried with allowedNewTables  --- but with no result !

**Comment by sgmcgill** [comment]
I've got the same problem. What and where I need to configure to enable the Attachment button. In the fluid template is an mmf:authentication.ifAccess with accessType="newAttachment". Where do I need to set this authentication Type.

**Comment by magu81** [comment]
tried it with all versions Available -  no success !!   Can anybody deiver an example, how to configure it, to enable Attachements etc .pp.. !?

**Comment by velletti** [comment]
in Backend -> List -> Forum you should be able to add the Access Type newAttachment. 

You need to repeat this for EACH Forum !
set login level to "LoginUser" or restrict it to a specific user Group (or repeat it for all user Groups)

It is the same like Access Rights to CREATE , EDIT and moderte:
you need to create the "read" , newTopic" "newPost" "editPost"  "newAttachment" and for shure also for a userGroup "moderate" 

after this you should have in the db table 
typo3forum_domain_model_forum_access a new entry 

If you have the Button "NewTopic" and just miss the new Attachment Button, take a look riectly to that database table to see what is inside ... 

if you have so many different usergroups, like prospects , customers, customers with service Contract, betatester, alphatester, developer, moderator,  students, and some more ... you will finally will no set the access rights in backend : i copy them from a specific Forum directly in the database : -)



The Login user Must

**Comment by velletti** [comment]
PS if you are on TYPO3 7.6, maybe the ifAccessViewhelper will not work :

this
 typo3-forum/Classes/ViewHelpers/Authentication/IfAccessViewHelper.php

uses RenderChild like the Old If Viewhelpers but this in m.O. does not work any more 
 
repalce the Code after the namespace line with this :   
if it works, (after Clear Cache in Install Tool!!!) i can try to update the code of the exteension  
`
/**
 *
 * ViewHelper that renders its contents if the current user has access to a
 * certain operation on a certain object.
 *
 * @author     Martin Helmich <m.helmich@mittwald.de>
 * @package    MmForum
 * @subpackage ViewHelpers_Authentication
 * @version    $Id$
 *
 * @copyright  2010 Martin Helmich <m.helmich@mittwald.de>
 *             Mittwald CM Service GmbH & Co. KG
 *             http://www.mittwald.de
 * @license    GNU Public License, version 2
 *             http://opensource.org/licenses/gpl-license.php
 *
 */
class IfAccessViewHelper extends \TYPO3\CMS\Fluid\ViewHelpers\IfViewHelper {
	/**
	 * Initialize arguments
	 * @throws \TYPO3\CMS\Fluid\Core\ViewHelper\Exception
	 */
	public function initializeArguments(){
		$this->registerArgument('object', 'object', 'The object for which the access is to be checked');
		$this->registerArgument('accessType', 'string', 'The operation for which to check the access');
		parent::initializeArguments();
	}
	/**
	 * Evaluate
	 * @param array|null $arguments
	 * @return bool
	 */
	protected static function evaluateCondition(array $arguments = null) {
		/**
		 * @var \Tx_MmForum_Domain_Repository_User_FrontendUserRepository $frontendUserRepository
		 */
		$frontendUserRepository = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('Tx_MmForum_Domain_Repository_User_FrontendUserRepository');
		$evaluate = false;
		if($arguments['object'] instanceof \Tx_MmForum_Domain_Model_AccessibleInterface) {
			if($arguments['object']->checkAccess($frontendUserRepository->findCurrent(), $arguments['accessType'])){
				$evaluate = true;
			}
		}
		return $evaluate;
	}
}`

**Comment by velletti** [comment]
see also 
[IfAccessViewhelper.txt](https://github.com/mittwald/typo3-forum/files/461468/IfAccessViewhelper.txt)

**Comment by magu81** [comment]
thx,

 i run with typo3 6.2.25.

I tried it, but can't see any ,,Attachements" in the Access right's, just READ, CREATE, EDIT, DELETE, MODERATE ... are available.

Could it be with the wrong sr_feuser-extension that this caused the unavailability of the function ?

**Comment by velletti** [comment]
yes, you are right ... in TCA of the forum access the Option newAttachment is gone since this cahnge 

https://github.com/mittwald/typo3-forum/commit/92283c347cf14331c586a9e5204f70e8ca896e37#diff-e5064b7818269b0908457fdf1278860c


if you add 
	[$lllPath . 'operation.newAttachment', 'newAttachment'],

after : 
 [$lllPath . 'operation.editPost', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_EDIT_POST],

in 

 Configuration/TCA/tx_typo3forum_domain_model_forum_access.php
it Will Work again .. Looks like a real bug ...

**Comment by velletti** [comment]
... but as i saw that the lokal Lang File was also modified and there is removeved the "New Attachment" string, it looks like a bug in the Template ... so someone thinks there should not be the separate Right to make a difference between Create Post and add Attachment ... 

so correct your Tempalte an change 
 mmf:authentication.ifAccess with accessType="newAttachment".
to
 mmf:authentication.ifAccess with accessType="newPost". ?? 
maybe enough .. 

(i still rely on my version WITH different behavior ...

**Comment by magu81** [comment]
access to ,,Attachement" is chooseable ... but getting in frontend with ,,create new topic":

Oops, an error occurred!

The form field "tx_typo3forum_pi1[attachments][][name]" is invalid. Reason: "[]" used not as last argument, but somewhere in the middle (like foo[][bar]).

More information regarding this error might be available online.


############################

locallang_db is modified:

			<label index="tx_typo3forum_domain_model_forum_access.operation.deletePost">Delete post</label>
			**<label index="tx_typo3forum_domain_model_forum_access.operation.newAttachment">Post attachments</label>**
			<label index="tx_typo3forum_domain_model_forum_access.negate">Negate</label>


tx_typo3forum_domain_model_forum_access.php : 

				'items' => [
					[$lllPath . 'operation.read', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_READ],
					[$lllPath . 'operation.newTopic', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_NEW_TOPIC],
					[$lllPath . 'operation.newPost', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_NEW_POST],
					[$lllPath . 'operation.editPost', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_EDIT_POST],
					[$lllPath . 'operation.deletePost', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_DELETE_POST],
					[$lllPath . 'operation.moderation', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_MODERATE],
					**[$lllPath . 'operation.newAttachment', 'newAttachment'],**
									
				],

/typo3_forum/Resources/Private/Templates/Standard/Topic/New.html    also to:


				<mmf:authentication.ifAccess object="{forum}" **accessType="newPost">**
				<b:form.row llLabel="Topic_New_Attachments">
					<f:if condition="{post.attachments}">
						<f:for each="{post.attachments}" as="attachment">
							<div>
								{attachment.filename},
								<mmf:format.fileSize>{attachment.filesize}
</mmf:format.fileSize>
							</div>

**Comment by jensengelmann** [comment]
I stumbled upon the same problem... and there's an easy fix...

The upload form name in the standard template is just missing an array indicator ... take a look at the bootstrap template. There the upload form looks like this:

`
<f:form.upload name="attachment[0]"/>
`

...while in the standard template it looks like this:

`
<f:form.upload name="attachment[]"/>
`

Just add a '0' and you'll be fine.

Generally it'll be interesting if dropping the attachment access level was intended. If so the templates need to be cleaned up.

**Comment by jensengelmann** [comment]
Oh boy... 

First of all we need to set the encoding type of the form to multipart/form-data. This is of course done in the according fluid template:
```xml
<f:form name="post" object="{post}" controller="Post" action="{action}" id="post" enctype="multipart/form-data">
```

Next thing I stumbled upon was a problem in the AttachmentService.php (https://github.com/mittwald/typo3-forum/blob/develop/Classes/Service/AttachmentService.php)... there we have a call to a non-defined function (...->getTCAConfig()) and a mkdir with a string as $mode argument -> must be int
```php
//Create dir if not exists
$tca = $GLOBALS['TCA']['tx_typo3forum_domain_model_forum_attachment'];
$path = $tca['columns']['real_filename']['config']['uploadfolder'];
if(!file_exists($path)) {
	mkdir($path,0775,true);
}
```

Final round... now let's have a look at the AttachmentModel (https://github.com/mittwald/typo3-forum/blob/develop/Classes/Domain/Model/Forum/Attachment.php). The first thing I encountered was the phpdoc definition of the $post variable... I had to use the FQCN.
```php
/**
 * The attachment file name.
 * @var \Mittwald\Typo3Forum\Domain\Model\Forum\Post
 * @lazy
 */
protected $post;
```
Then I got a php deprecation warning for the following statement for statically calling `\TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager::getTypoScriptSetup()` and also an fatal error because it was calling methods on null (both in the `initializeObject()` function). The issue has already been discovered (https://github.com/mittwald/typo3-forum/issues/91). So I used the $GLOBALS method to get the typoscript setup:
```php
public function initializeObject() {
	$ts = $GLOBALS['TSFE']->tmpl->setup;
	$this->settings = $ts['plugin']['tx_typo3forum']['settings'];
}
```
Okay... for clean up reasons I also dumped `$typoScriptService` in the AttachmentModel definition because we don't need it anymore.

So long... it now works for me... an maybe the Mittwald guys can adapt the code ;-)

**Comment by magu81** [comment]
This is of course done in the according fluid template: ===> Which file ... where to find ?

**Comment by jensengelmann** [comment]
@magu81 Depends on the template you use: for the standard template it's https://github.com/mittwald/typo3-forum/blob/develop/Resources/Private/Partials/Standard/Post/Form.html, if you are using the bootstrap template you'll find the template here: https://github.com/mittwald/typo3-forum/blob/develop/Resources/Private/Partials/Bootstrap/Post/Form.html

**Comment by magu81** [comment]
now i got no more errors - but nevertheless , .. the upload (attached image [jpg]) isnt shown in the post !

**Comment by magu81** [comment]
i belive that the mittwald guys should release a 1.0.4 Version of the typo3_fourm which includes the Attachement upload in the forum again -- it make sense !!

**Comment by jensengelmann** [comment]
@magu81 Please check your upload folder (should be something like /uploads/tx_typo3forum/attachments) - I guess it doesn't have write permissions for the www-data since it might have been created by the mentioned mkdir function without the proper $mode settings (default permissions should be 0777 but were 0655 in my case).

The whole directory checking and creating part should be revised. I don't think it's fail-safe by now. And why are the directories not created by the 'createDir' function in  ext_emconf.php?

**Comment by magu81** [comment]
the folders are now createtd, --- but still no attachements uploaded

**Comment by magu81** [comment]
@jensengelmann --- can you send me your ,,typo3_forum" extension ?

**Comment by magu81** [comment]
@jensengelmann - can you send me your modificated typo3_forum as an archive ? in my case, it won't work !

**Comment by jensengelmann** [comment]
@magu81 - we are implementing a highly customized version of the original extension, so I don't think it'll help you. All in all the whole file upload had to be reworked. We added the things we needed, like the possibility of deleting files when updating a post. But we tailored everything to our needs without thinking about a more general solution.

**Comment by magu81** [comment]
@jensengelmann -- nun gut, jedenfalls verstehe ich nicht, warum der Upload nicht funktioniert, Datei auszuwählen, hochzuaden, aber ncihts im Post zu sehen, ebenso wenig eine Fehlermeldung und auch ncihts im upload/typo3_forum/-Folder ... komische Sache !

**Comment by jensengelmann** [comment]
You should debug the create/update action... look for the php $_FILES array. If it's empty when you're trying to submit files, there might be a problem with the form itself (e.g. wrong name for the file input field).

**Comment by bihor** [comment]
Hier noch ein entscheidender Fehler:
in Classes/Domain/Model/Forum/Post.php
Zeile 352:
```
	 * @validate $attachments \Mittwald\Typo3Forum\Domain\Validator\Forum\AttachmentPlainValidator 
	 * anstatt Tx_Typo3Forum_Domain_Validator_Forum_AttachmentValidator
	 *
	 * @return void
	 */
	public function setAttachments(ObjectStorage $attachments) {
```

**Comment by bihor** [comment]
Ein weiteres Problem: die oben genannte Lösung:
`public function initializeObject() {
    $ts = $GLOBALS['TSFE']->tmpl->setup;
    $this->settings = $ts['plugin']['tx_typo3forum']['settings'];
}`
funktioniert nicht, wenn isValid in AttachmentPlainValidator hier aufgerufen wird:
`      /** Creates a new post.
	 *
	 * @param Topic $topic The topic in which the new post is to be created.
	 * @param Post $post The new post.
	 * @param array $attachments File attachments for the post.
	 *
	 * @validate $post \Mittwald\Typo3Forum\Domain\Validator\Forum\PostValidator
	 * @validate $attachments \Mittwald\Typo3Forum\Domain\Validator\Forum\AttachmentPlainValidator
	 */

	public function createAction(Topic $topic, Post $post, array $attachments = []) {`
Das settings-Array sieht dann so aus:
`array(1) { [0]=> string(0) "" }`

Hiermit funktioniert es jedenfalls:
`
  $ts = $GLOBALS['TSFE']->tmpl->setup;
  if ($ts[0] == '') {
    $typoScriptService = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Service\\TypoScriptService');
    $ts = $typoScriptService->convertTypoScriptArrayToPlainArray(\TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager::getTypoScriptSetup());
  }
  $this->settings = $ts['plugin']['tx_typo3forum']['settings'];
`

Allerdings sind auch in /Classes/Domain/Validator/Forum/AttachmentPlainValidator.php
noch weitere Fehler!
Statt
`if ($attachment->$attachment['size'] > $attachmentObj->getAllowedMaxSize) {`
muss es natürlich so heissen:
`if ($attachment['size'] > $attachmentObj->getAllowedMaxSize) {`

Ausserdem wird im Fehlerfall nicht diese Meldung:
`$this->addError('The submitted file is to big!.', 1371041888);`
sondern eine andere, allgemeine Meldung ausgegeben.
Da scheint es noch ein Problem mit addError zu geben!

**Comment by jensengelmann** [comment]
As i wrote: I think the whole file upload and attachment handling has to be rethought/reworked. E.g. there's no delete function for an already uploaded attachment.

**Comment by bihor** [comment]
Well, it works with the changes from above. I think it is not neccessary to rework everything.

**Comment by magu81** [comment]
@bihor -- da ich schon ewig versuche daran herumzudoktorn -  kannst Du mir vielleicht Dein modifiziertes Paket irgendwie zukommen lassen !?

**Comment by magu81** [comment]
@bihor  --in welchem FIle genau muss:

Hiermit funktioniert es jedenfalls:

 $ts = $GLOBALS['TSFE']->tmpl->setup; if ($ts[0] == '') { $typoScriptService = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Service\\TypoScriptService'); $ts = $typoScriptService->convertTypoScriptArrayToPlainArray(\TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager::getTypoScriptSetup()); } $this->settings = $ts['plugin']['tx_typo3forum']['settings']; 

gesetzt werdem !?

**Comment by jensengelmann** [comment]
@bihor Well, we've just encountered another problem with the file download... the downloadAction in the PostController returns headers and a view error message in the standard configuration. This is no problem for robust file types like most images, but easily corrupt others (like pdf or word).

Easy fixes, for sure, but the whole file up- and download jsut doesn't work out of the box...

Maybe you can confirm this beaviour (since we are working on a highly customized version of the extension) and open another issue...

**Comment by bihor** [comment]
> Final round... now let's have a look at the AttachmentModel (https://github.com/mittwald/typo3-forum/blob/develop/Classes/Domain/Model/Forum/Attachment.php). 

Thats the file where you need to correct the initializeObject().

I am not sure if I am allowed to publish my version. I will ask the chief.

**Comment by bihor** [comment]
Yes, I can confirm, that a download of a PDF will not work.
Is there a solution?

Noch ein Nachtrag zu dem allgemeinen Fehler:
da im Fehlerfall nur eine allgemeine Fehlermeldung ausgegeben wird, sollte
man bedenken, dass standardmäßig nur Anhänge mit max. 4 kB erlaubt sind.
Das ist natürlich ein Witz. Ich habe bei attachment.allowedSizeInByte noch drei 0en angehängt...

**Comment by magu81** [comment]
so we might hope that MITTWALD will release a 1.0.4 Version soon !!!

**Comment by jensengelmann** [comment]
@bihor We fixed it, but it's not a real solution.

For getting rid of the header data, we added a new page type (in our case we used an already existing ajax page type) without any header data and added the page type to the download links in the frontend. Maybe a solution with a GPvar condition which checks the controller and action works too.

In the downloadAction we added an `exit();` at the end, to prevent the call for the view. Maybe an empty template for the downloadAction does the same.

**Comment by bihor** [comment]
This is my solution for download-problem:
in Classes/Controller/PostController.php -> downloadAttachementAction:

$attachment->increaseDownloadCount();
$this->attachmentRepository->update($attachment);
$headers = array(
		'Pragma'                    => 'no-cache',
		'Expires'                   => gmdate('D, d M Y H:i:s') . ' GMT',
		'Cache-Control'             => 'must-revalidate, post-check=0, pre-check=0',
		'Cache-Control'             => 'public',
		'Content-Transfer-Encoding' => 'binary',
		'Content-Description'       => 'Download-File',
		'Content-Type'              => $attachment->getMimeType(),
		'Content-Length'            => $attachment->getFilesize(),
		'Content-Disposition'       => 'attachment; filename=' . $attachment->getFilename()
);
foreach($headers as $header => $data)
	$this->response->setHeader($header, $data);
$this->response->sendHeaders();
readfile($attachment->getAbsoluteFilename());
exit;

Furthermore I have added a new page with the Forum and there I put this TypoScript:
config {
  disableAllHeaderCode = 1
  disableBodyTag = 1
  disableCharsetHeader = 1
}

Then I have changed the link to the attachement in the Partial Post/Single.html and added the pageUid to the link.
It should work, but it didn´t. Finally I added the action downloadAttachment to ext_localconf.php and created an empty file DownloadAttachement.html in the Post-directory.
I don´t know, why I needed the last step, but now it works correctly.
I have tested it with "Live HTTP Headers".

**Comment by bihor** [comment]
OK, my solution for initializeObject in Classes/Domain/Model/Forum/Attachment.php worked only on the Testserver. This is the correct solution:
	public function initializeObject() {
		$ts = $GLOBALS['TSFE']->tmpl->setup;
		if (!is_array($ts['plugin']) && !is_array($ts['plugin.'])) {
			$typoScriptService = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Service\\TypoScriptService');
			$ts = $typoScriptService->convertTypoScriptArrayToPlainArray(\TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager::getTypoScriptSetup());
		}
		$this->settings = $ts['plugin']['tx_typo3forum']['settings'];
	}

The problem is, that $GLOBALS['TSFE']->tmpl->setup is empty in one case and in the other case
$typoScriptService = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Service\\TypoScriptService');
can not be used. So we need both solutions and a good if-statement. I have changed the if-statement now, but I am not sure if to use $ts['plugin'] or $ts['plugin.'].

**Comment by bihor** [comment]
Leider war die Lösung auch nicht korrekt. Es ist verwirrend, aber wahr:
ein Array enthält Punkte am Ende der Keys, das andere nicht. Also muss es so aussehen:
$this->settings = $ts['plugin']['tx_typo3forum']['settings'];
if (!$this->settings) {
  $this->settings = $ts['plugin.']['tx_typo3forum.']['settings.'];
  $this->settings['attachment'] = $ts['plugin.']['tx_typo3forum.']['settings.']['attachment.'];
}
Damit sollte es aber endlich gehen.

**Comment by jensengelmann** [comment]
@bihor There's a tool for that: TypoScriptService->convertTypoScriptArrayToPlainArray (https://typo3.org/api/typo3cms/class_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_service_1_1_typo_script_service.html#a72aaf68b5db8f8624dd65b680e5b7697)

**Comment by bihor** [comment]
An @magu81 und Mittwald: unser funktionierendes Forum (in Bezug auf Anhänge) kann man für eine Weile hier finden: [Version 10.0.3](http://www.fixpunkt.com/fileadmin/typo3_forum_10-0-3.zip)
Die meisten Änderungen kann man unter dem Stichwort "KGB" finden...

**Comment by pstranghoener** [comment]
@bihor Would be cool, if you can make pull request for it so that everyone can use it. 

Best Regards Philipp

**Comment by magu81** [comment]
@bihor  -- besten Dank - allerdings funktioniert auch hier der Upload nicht, auch wird das PermissionObjekt ,,attachement [Wert nicht erlaubt]" nicht im Backend angezeigt.

**Comment by magu81** [comment]
@bihor - ich bin doch richtig der Annahme dass ich hierzu am Quellcode nichts mehr zu ändenr habe !?

**Comment by magu81** [comment]
Nachdem ich nun:

if you add 
[$lllPath . 'operation.newAttachment', 'newAttachment'],

after : 
[$lllPath . 'operation.editPost', \Mittwald\Typo3Forum\Domain\Model\Forum\Access::TYPE_EDIT_POST],

in

Configuration/TCA/tx_typo3forum_domain_model_forum_access.php

eingefügt und ebenfalls in 

locallang_db folgendes nachgetragen habe

        <label index="tx_typo3forum_domain_model_forum_access.operation.deletePost">Delete post</label>
        **<label index="tx_typo3forum_domain_model_forum_access.operation.newAttachment">Post attachments</label>**
        <label index="tx_typo3forum_domain_model_forum_access.negate">Negate</label>


ist das PermissionObjet ,,attachemtn" wieder verfügbar -- dennoch lädt es nichts hoch !

**Comment by pstranghoener** [comment]
@magu81 Please write in english! Thanks!

**Comment by magu81** [comment]
@pstranghoener .. done !

**Comment by bihor** [comment]
As you can see in my templates, I didn´t used the newAttachment-check.
Yes, you are right, I haven´t solved that problem, but when you delete or replace that check in your template, it works. I changed it to newPost, because of this suggestion from above:

> so correct your Tempalte an change 
mmf:authentication.ifAccess with accessType="newAttachment".
to
mmf:authentication.ifAccess with accessType="newPost". ??

**Comment by magu81** [comment]
i already did this:

<mmf:authentication.ifAccess object="{forum}" accessType="newPost">
				<b:form.row llLabel="Topic_New_Attachments">
					<f:if condition="{post.attachments}">
						<f:for each="{post.attachments}" as="attachment">
							<div>
								{attachment.filename},
								<mmf:format.fileSize>{attachment.filesize}</mmf:format.fileSize>
							</div>
						</f:for>
					</f:if>
					<f:form.upload name="attachments[0]"/>

But it won't work !

**Comment by magu81** [comment]
its unbelivable - if i create a new topic - i can't create this with attachement(s) ---- BUT if i reEDiT my Post, i'm able to place attachements on it -  and the download of the Attachements working also.

Im not sure what i did wrong!?!?!?

**Comment by magu81** [comment]
now im realized the Attachements function whats meant with -  its a nice feature - but what im still looking for is a way to place IMAGES as an Object in my Post and not only as an attachement itself.  i will post TEXT with embeeded IMAGES !!

i'm also wasnt able to use the BBcode Funktion -  theres only the InputForm with no chance to  markup the Text (bold;italic;code;images;smileys etc.pp)

**Comment by pstranghoener** [comment]
Our Developr will look at the Attachment function in the next weeks that it work correct. But we are not developing anything special functions. 

The BBCode Topic is not part of this topic, but here i a small hint did  you create the bbcodes items in the backend?

**Comment by magu81** [comment]
@pstranghoener  -did you create the bbcodes items in the backend ?

No i didn't - how to create this stuff , with the forum-extension itself ?

**Comment by pstranghoener** [comment]
@magu81 Yes u have to create bbcode record in the listview in an folder in the backend... But once again thats the wrong topic.
