### ISSUE TITLE
TCA error

### ISSUE THREAD

**Issue by nicozerr** [mittwald/typo3-forum#152]
Hi.

In Configuration/TCA/tx_typo3forum_domain_model_stats_summary.php, you should replace:
`'sortby' => 'tstamp DESC',`
by
`'default_sortby' => 'ORDER BY tstamp',`

Same problem with Configuration/TCA/tx_typo3forum_domain_model_user_notification.php, you shoud replace:
`'sortby' => 'crdate DESC',`
by
`'default_sortby' => 'ORDER BY crdate',`

TYPO3 7.6.10
typo3_forum 1.0.3

**Comment by pstranghoener** [comment]
Please make a pull request for that. Thanks.
