### ISSUE TITLE
Unable to create topic

### ISSUE THREAD

**Issue by morphesus** [mittwald/typo3-forum#156]
Hello everyone!

Maybe someone of you already know this issue to be unable to create topics with ACL's given, extended Website User and Usergroup. Also the TypoScript configuration is done, the static includes too. I found the issue #116, but my forum.js file looks clean and there is no static definition for any UIDs.

So, I have a TYPO3 6.2.27 running with just a few modifications, nothing special. I installed the forum using the Guide (http://typo3-forum.readthedocs.io/en/master/index.html). I also tried to install the forum on a local and fresh TYPO3 6.2.27 installation. On both installations I got the same problem mentioned above: I'm not able to create topics in the frontend. It makes no difference to be logged in or not. Changing the record type doesn't change anything - the behaviour remains the same.

Does anyone have a solution for this issue?
If you need any further information, please let me know!

Thank you very much in advance!

Kind regards
Enrico Ludwig

**Comment by pstranghoener** [comment]
Hello,

did you give your users and your usergroups the typo3_forum user rights? 

Best Regards 
Philipp

**Comment by morphesus** [comment]
Hi @pstranghoener and thanks for your response!

Yes, the users have the ACL permissions (Read, Write, Edit, Create Topic) as well as the correct record type.

Kind regards
Enrico Ludwig

**Comment by pstranghoener** [comment]
Then there must be something else misconfigured.

**Comment by morphesus** [comment]
Maybe, yes.

I followed the instructions from readthedocs.io multiple times, even on a completly blank system but I always got the same result. Maybe there is something wrong in the documentation ...

**Comment by pstranghoener** [comment]
I don't think that there is something wrong in the documentation, there are enough people how are using it like this. And we are using it on typo3.net also.

**Comment by morphesus** [comment]
But what could be the issue? I revised all permissions many times - much more possibilities aren't given. Or have I got that wrong?

**Comment by pstranghoener** [comment]
I don't know that you have missconfigured, it is the same as looking into a glass sphere for me... Sorry to say that...

**Comment by morphesus** [comment]
Maybe it helps a bit, when I post some screenshots:

This is my ACL configuration
![image](https://cloud.githubusercontent.com/assets/1678039/18705436/87aa7a66-7fee-11e6-901e-55cd312407c0.png)

The record type for the user is set
![image](https://cloud.githubusercontent.com/assets/1678039/18705463/a4ac6e80-7fee-11e6-9882-37b1a9d47879.png)

User settings are still default
![image](https://cloud.githubusercontent.com/assets/1678039/18705478/beaabe7c-7fee-11e6-980b-36c8adcbdc24.png)
![image](https://cloud.githubusercontent.com/assets/1678039/18705490/ca21fef0-7fee-11e6-885d-3ce87af16863.png)

The forum plugin on a page
![image](https://cloud.githubusercontent.com/assets/1678039/18705534/e9b87a14-7fee-11e6-8998-4b23db0102b5.png)

And this is how it looks in FE (I'm logged in with the user shown in the screenshot above)
![image](https://cloud.githubusercontent.com/assets/1678039/18705579/1b569ace-7fef-11e6-989a-9db4e8df5cc0.png)

I tried the same setup with a blank TYPO3 installation, same result.

Thank you in advance!

**Comment by pstranghoener** [comment]
Thats easy look at at the first screenshot at the point "login level". You have to choose the user group there...

**Comment by morphesus** [comment]
Yeah, thanks for closing the topic without waiting for my response ...
I also tried this, here are some screenshots:

This is the user:
![image](https://cloud.githubusercontent.com/assets/1678039/18706664/367b6d8a-7ff3-11e6-9988-ba350153a5a1.png)

Here are the ACLs:
![image](https://cloud.githubusercontent.com/assets/1678039/18706763/91ddb8d6-7ff3-11e6-922c-0705807fcc23.png)
![image](https://cloud.githubusercontent.com/assets/1678039/18706772/9bc6a4b6-7ff3-11e6-94e2-423e6e39d806.png)
![image](https://cloud.githubusercontent.com/assets/1678039/18706785/a4ba4596-7ff3-11e6-9d74-f246c8681a99.png)

And there is still no "Create Topic" button.

**Comment by pstranghoener** [comment]
Thats screenshots doesnt help me alot, did you clear caches and logout and login again and al these things? I am sorry say but its an free extension and the can't give support for all the misconfugrations the users are doing.

**Comment by morphesus** [comment]
Hi there

Yes, I cleared all caches (also with the Install tool)

I know that it's not that easy to help remotely especially if it's an Open Source project, but I'm thankful that you try to help me with this.

There is not that much of configuration done, as I said: I already tested it on a completely blank TYPO3 installation. Maybe it helps a bit, when you also see my TypoScript configuration for the typo3_forum extension:

```typoscript
plugin.tx_typo3forum {
            persistence {
                    storagePid = 186
                                    }
            settings {

                    pids {
                            Forum = 185
                    }
            }
    }
```

The storagePid points to this system folder:
![image](https://cloud.githubusercontent.com/assets/1678039/18710244/7bacfa5c-8004-11e6-89ea-af88ff46e005.png)
![image](https://cloud.githubusercontent.com/assets/1678039/18710251/85f1caec-8004-11e6-93c4-00aa9be5f51e.png)

The Forum pid points on the page, where the Forum plugin is.

Kind regards
Enrico Ludwig

**Comment by DavidBruchmann** [comment]
@pstranghoener 
> I am sorry say but its an free extension and the can't give support for all the misconfugrations the users are doing.

When Mittwald published mm_forum, support-forums have been full with it.
If you search in mailinglists or forums now for typo3_forum you find nearly nothing.
It's easy to blame Mittwald for it and perhaps that's not fair. But if I don't mistake they started the project end perhaps expected more support from the community. Now any work seems running too limited to get the attention from enough users and the community.
If a few interested users still are left alone with their problems, then the project is getting abandoned and ignored by users completely.

Blaming @morphesus who read the manuals over and over again is not fair and not helping. Mittwald should concentrate to get the community back if possible instead of blaming those who try hard in installing but never think about any errors that could prevent the forum working.

**Comment by DavidBruchmann** [comment]
One thing I still forgot to mention:
Closing unsolved issues never even helps yourself to get the forum sometime stable.

I don't want to blame anyone but I think you @pstranghoener miss some issues with the current state of the forum, no matter if it's depending on a special environment or some faults made by users or something else. Either documentation or code have to be fixed to get more people attracted again, this measure is not about code-quality and details but it's a matter of amount of people and a potential large community, which in the moment related to the forum is dead. If you think further it's a matter of people who decide either for Mittwald or against it for hosting and perhaps other services.
