### ISSUE TITLE
Remove the ::class for PHP 5.4 compatibility

### ISSUE THREAD

**Issue by pstranghoener** [mittwald/typo3-forum#157]
Please remove the following classes.....

$ git grep '::class' | cat  
Classes/ViewHelpers/IfInstanceOfViewHelper.php:        $this->registerArgument('object', AbstractDomainObject::class, 'Object to check', true);
Classes/ViewHelpers/User/IfSubscribedViewHelper.php:        $this->registerArgument('object', SubscribeableInterface::class, 'Object to check', true);
Classes/ViewHelpers/User/IfSubscribedViewHelper.php:        $this->registerArgument('user', FrontendUser::class, 'className which object has to be', false, null);
Resources/Private/Libraries/GeSHi/geshi/oorexx.php:            '::attribute', '::class', '::constant', '::method',

**Comment by macjohnny** [comment]
related to #147
