### ISSUE TITLE
widget "who is online" always shows "no members online"

### ISSUE THREAD

**Issue by sxbxstxxn** [mittwald/typo3-forum#160]
I know that there are other users online, but it's not working in the widget. All the users have the extende Record type "typo3_forum user" and I choose the correct folder where all the FE Users are stored in the plugin.
Any ideas why it's not working?

**Comment by macjohnny** [comment]
@kpurrmann please note that `initializeObject()` is not getting called if the repository is injected. 
see also https://github.com/mittwald/typo3-forum/pull/168

**Comment by macjohnny** [comment]
@kpurrmann this is what I also expected. However, at least with TYPO3 6.2 this did not work for in the ajax requests, which is why I had to implement it elsewhere.

**Comment by kpurrmann** [comment]
@macjohnny I set up several environment and everything seems to work fine. May you could checkout this branch and test it on your own?

**Comment by macjohnny** [comment]
@kpurrmann it might have been due to the fact that i implemented `initializeObject()` in an xclass of `ForumRepository`. if it works fine for you, i believe you ;-)
