### ISSUE TITLE
Nesting level to deep in UserController again

### ISSUE THREAD

**Issue by sashbash** [mittwald/typo3-forum#161]
The following error occurs sometimes (not always) when a topic has subscribers.

Nesting level too deep - recursive dependency? in /var/www/html/typo3conf/ext/typo3_forum/Classes/Service/Notification/NotificationService.php on line 110

Solution (same as in bug #52 ) compare uids instead of whole object.

Replace:
`if ($subscriber != $post->getAuthor()) {`

with
`if ($subscriber->getUid() != $post->getAuthor()->getUid() ) {`

Best regards
Sascha

**Comment by macjohnny** [comment]
@sashbash we got the same error, too.
thanks for the suggested solution, i will make a pull request for this.

**Comment by macjohnny** [comment]
@martin-helmich can you merge this?

**Comment by martin-helmich** [comment]
Fixed in #165
