### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/typo3-forum#6]

**Comment by mojobsb** [comment]
Is there a documentation already?
I'm new to typo3_forum / mm_forum. Which is the most fitting documentation from mm_forum?
It's hard to use the extension without any clue how to install and configure....

**Comment by alat54** [comment]
Hi, 

I need it too :( i don't find where i can create a topic on the front, maybe it's a mistake in config but i don't know what i am supposed to do to create a functionnal forum... 
A documentation in really really necessary please

Thanks

**Comment by stefan72** [comment]
I think if there would be a small documentation, to get the forum installed and running, more uses would use it. And with a good base of users, some might as well be interested to contribute. Strongly agree wit above comments.

**Comment by pstranghoener** [comment]
Hey everyone, 

we are working on an detailed installation guidance which will be ready soon.

Best Regards

**Comment by mojobsb** [comment]
There is some documentation on how to install already, even if it's not rendered correctly.
But it ends at the point where it says "no forums found" in the frontend. It would really need some advice how to configure the plugins / userrights. Trial and error didn't help me and that's my major skill ;-)

**Comment by pstranghoener** [comment]
Thats why we are working on the documentation as i said before.

**Comment by MajorTom13** [comment]
I'd like to help. What can I do?

Von meinem iPhone gesendet

**Comment by pstranghoener** [comment]
Documentation is updated and will updated continuously. 

http://typo3-forum.readthedocs.org/en/latest/
