### ISSUE TITLE
TYPO3 7.X Compatibility

### ISSUE THREAD

**Issue by sdiercks** [mittwald/typo3-forum#86]
Full compatibility for TYPO3 7.X (currently @ 7.5) needed - someone working on it?

**Comment by martin-helmich** [comment]
@pstranghoener, do you have any plans concerning 7.5 compatibility?

**Comment by alat54** [comment]
Hi, and on 7.6 LTS?

**Comment by pstranghoener** [comment]
Hey,

first release is now available in TER http://typo3.org/extensions/repository/view/typo3_forum 
It it compatible from 6.2.0 to 7.x
