### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by silversight** [mittwald/typo3-forum#88]
Hi..

I hope this is the right place my question and get some information about my problen not beeing able to install typo3-forum on a clean Mittwald account with TYPO3 6.2.15

importing the extension via Extension Module ist possible; I get an import error. 
And´copying the ext into the ext folder, turns the ext. module into a white page.

All dependencies are installes, properly.

Are there any hidden hints to be known???

Thanks, Tom.

**Comment by selim-hausformat** [comment]
Guten Tag

Vielen Dank für Ihre Nachricht. 
Diese Adresse ist nicht mehr in Betrieb. Bitte wenden Sie sich an Reto Schmid (reto@hausformat.com) oder an unseren Support unter support@hausformat.com.

Freundliche Grüsse
Selim Imoberdorf

—
.hausformat
Rohrerstrasse 20
5000 Aarau
+41 (0)62 823 86 80
www.hausformat.com

Folgen Sie uns:
www.facebook.com/hausformat
plus.google.com/+hausformat

Benötigen Sie Unterstützung?
Wir helfen Ihnen gerne
über unsere Supportadresse:
support@hausformat.com

**Comment by pstranghoener** [comment]
Hey, 

there will be a final release from the extension in the TER and than the problem will be obsolete. For the Installation instructions there will be a documention.

Best Regards

**Comment by silversight** [comment]
Hi....
thanks for the info. is there a date planed? (at least approx.);
Probably you wait until the relase of the LTS, right?
