### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by alat54** [mittwald/typo3-forum#89]
Hi, 

I have tested the new version on TER and on a 7.6 typo3 plateform.
But i couldn't find the way to login in the forum, with the basic login form on typo3, i have still 

-- connection block
Login successful
You are now logged in as 'admin'
-- dashboard block
Whoops!
You need to be logged in to view your own subscriptions. 

Can you help me?

Thanks

**Comment by velletti** [comment]
I think it is missing just a part of documentation:

Edit the Usergroup you gae access to the Forum:
in TYPO3 backend (or look into databes tabel fe_groups)

It must be tx_extbase_type set to  Tx_Typo3Forum_Domain_Model_FrontendUserGroup

same for You User Account:
It must be tx_extbase_type set to   Tx_Typo3Forum_Domain_Model_FrontendUser

See typosrcipt setup:
Configuration/TypoScript/setup.txt

Mittwald\Typo3Forum\Domain\Model\User\FrontendUser {
		mapping {
			tableName = fe_users
			recordType = Mittwald\Typo3Forum\Domain\Model\User\FrontendUser

and
TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup.subclasses {
		Mittwald\Typo3Forum\Domain\Model\User\FrontendUserGroup = Mittwald\Typo3Forum\Domain\Model\User\FrontendUserGroup
	}

**Comment by alat54** [comment]
Oh it's named typo3_forum group and typo3_forum user in my BE !
I searched Tx_Typo3Forum_Domain_Model_FrontendUser.

My bad sorry.
Thanks for your help
