### ISSUE TITLE
Hyperlinks in Forum list do not link

### ISSUE THREAD

**Issue by teuniz-nl** [mittwald/typo3-forum#90]
Hyperlinks in the forum list do not link. The href attribute is empty. Did I miss a setting?

Is there a basic installation guide for typo3_forum now that it is in TER?

Thanks in advance!

**Comment by velletti** [comment]
this can have 2 reasons:
the PID Settings are empty or pointing to a not reachable page ( not logged in etc) :

plugin.tx_typo3forum.settings {
pids {
		Forum =
		UserShow =
		UserList =
		QuestionList =
		AllQuestions =
	}


or
The field "display_pid in the TABLE tx_typo3forum_domain_model_forum_forum has no value

it depends on you templates .. see the used Template CODE ...

**Comment by teuniz-nl** [comment]
Thank you.

The forums are in sysfolder 25. So I set pids.forum = 25.
The plugin is on page 26. The display_pid was 0, so I changed it manually to 26. 
No result. Or should I setup all pages first?

Btw: the users are stored on the same page and have access rights. The usergroup and user are extended with the typo3_forum. Did I miss something.

I have the feeling that I'm so close.

**Comment by velletti** [comment]
PID = SYS Folder will not work:
The IDs you have to enter are NORMAL  Pages: Solution: 
Create a Normal Page, Place the default Forum Plugin there and put this as pids.Forum = 
If you want to show a list of active users: 
Create a Normal Page, Place the  Forum Plugin, select User -> List  there and put this pida as pids.userList = save for the Features userShow ( Details of that user) , Open Questions List and All Questions list.

I think this is not a bug so i close this ..

**Comment by teuniz-nl** [comment]
Thank you. Finally, it works!
