### ISSUE TITLE
[CSS] Side effects

### ISSUE THREAD

**Issue by alat54** [mittwald/typo3-forum#94]
Hi, 

Is it possible to isolate the forum's css? When it's used with the introcution package for example, it break the package's skin.
It breaks the skin of tx_news too...

Thanks

**Comment by mavoIn** [comment]
hi,

can you make some examples? in my installation i had also "problems" first. after deactivating the bootstrap css via tsconfig i had no problems any more...

**Comment by alat54** [comment]
Hi, 

Yeah but all it's ok when i desactivate the bootstrap css? because i use it in all of my website...

Thanks

**Comment by alat54** [comment]
Hi, 

There are the screens
![withforum](https://cloud.githubusercontent.com/assets/10880836/12164568/dc062b44-b516-11e5-8790-a00afbf6dff1.png)
![withoutforum](https://cloud.githubusercontent.com/assets/10880836/12164567/dc038542-b516-11e5-96bd-6a1b81f82bd7.png)

You have when i had the forum template and when i don't add it...
If it's possible to add class to the css it could be great to don't break the base css of the introduction package

thanks
